flowchart TD
    subgraph Timer["OffTimer"]
        TimerCancel[["Cancel OffTimer<br/>(if running)"]]
        TimerCancel --> TimerStart["Start OffTimer<br/>(<i>delay</i> seconds)"]
        TimerStart --> TimerTimeout{{"Timeout?"}} -- No --> TimerTimeout
        TimerTimeout -- Yes --> EmitOff["Emit OFF"]
    end
        Input(["Input"]) --> EvaluateNewValue{"Evaluate<br>new_value"}
        EvaluateNewValue -- OFF --> TimerCancel
        EmitOff --> Output
        EvaluateNewValue -- ON --> CancelTimerForOn[["Cancel OffTimer<br/>(if running)"]]
        CancelTimerForOn --> EmitNewValue["Emit new_value"]
        EmitNewValue --> Output

