flowchart TD
 subgraph Timer["SettleTimer"]
        TimerCancel[["Cancel SettleTimer<br>(if running)"]] --> TimerStart["Start Settle Timer<br>(<i>delay</i> seconds)"]
        TimerStart --> TimerTimeout{{"Timeout?"}} -- No --> TimerTimeout
        TimerTimeout -- Yes --> RestoreSteady["Set steady=Yes"]
  end
    Input(["Input"]) --> EvaluateSteady{"Is steady?<br/>(default: Yes)"}
    EvaluateSteady -- No --> SetSteadyOn["Set steady = Yes"]
    SetSteadyOn --> EmitNewValue["Emit new_value"]
    EvaluateSteady -- Yes --> SetSteadyOff["Set steady = No"]
    SetSteadyOff --> TimerCancel
    EmitNewValue --> Output(["Output"])
